version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    runtime: nvidia # Activ GPU
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - ollama-docker

  open_api_backend:
    build: ../infrastructure/Open_API_Backend
    ports:
      - "8082:8082"
    volumes:
      - ../Open_API_Backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ollama-docker


networks:
  ollama-docker:
    external: false
